import type { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/website/',
          '/website/buyer',
          '/website/seller',
          '/website/blog/buyer',
          '/website/blog/seller',
          '/website/team',
          '/website/legal/',
          '/earlyaccess',
          '/auth',
          '/wholesale-pallet-liquidation',
          '/wholesale-liquidation-platform',
          '/online-liquidation-auctions',
        ],
        disallow: [
          '/buyer/deals',
          '/seller/dashboard',
          '/marketplace',
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/actions/',
          '*.json',
          '/earlyaccess/thankyou',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/website/',
          '/website/buyer',
          '/website/seller',
          '/website/blog/buyer',
          '/website/blog/seller',
          '/website/team',
          '/website/legal/',
          '/earlyaccess',
          '/wholesale-pallet-liquidation',
          '/wholesale-liquidation-platform',
          '/online-liquidation-auctions',
        ],
        disallow: [
          '/buyer/deals',
          '/seller/dashboard',
          '/marketplace',
          '/api/',
          '/admin/',
          '/private/',
          '/actions/',
          '/earlyaccess/thankyou',
        ],
      },
      {
        userAgent: ['Bingbot', 'Slurp'],
        allow: [
          '/',
          '/website/',
          '/website/buyer',
          '/website/seller',
          '/website/blog/buyer',
          '/website/blog/seller',
          '/website/team',
          '/website/legal/',
          '/earlyaccess',
          '/wholesale-pallet-liquidation',
          '/wholesale-liquidation-platform',
          '/online-liquidation-auctions',
        ],
        disallow: [
          '/buyer/deals',
          '/seller/dashboard',
          '/marketplace',
          '/api/',
          '/admin/',
          '/private/',
          '/actions/',
        ],
      },
      {
        userAgent: 'Applebot',
        allow: [
          '/',
          '/website/',
          '/website/buyer',
          '/website/seller',
          '/website/blog/buyer',
          '/website/blog/seller',
          '/website/team',
          '/website/legal/',
          '/earlyaccess',
          '/wholesale-pallet-liquidation',
          '/wholesale-liquidation-platform',
          '/online-liquidation-auctions',
        ],
        disallow: [
          '/buyer/deals',
          '/seller/dashboard',
          '/marketplace',
          '/api/',
          '/admin/',
          '/private/',
          '/actions/',
        ],
      },
    ],
    sitemap: 'https://www.commercecentral.io/sitemap.xml',
    host: 'https://www.commercecentral.io',
  }
} 